services:
  - type: web
    name: znk-snake-server
    env: node
    plan: free
    buildCommand: yarn install --frozen-lockfile; yarn workspace @znk/shared build
    startCommand: yarn workspace server start
    autoDeploy: true
    envVars:
      - key: CLIENT_ORIGIN
        sync: false

  - type: web
    name: znk-snake-client
    env: node
    plan: free
    buildCommand: yarn install --frozen-lockfile; yarn workspace @znk/shared build; yarn workspace client build
    startCommand: npx serve -s client/dist -l $PORT
    autoDeploy: true
    envVars:
      - key: VITE_SERVER_URL
        sync: false
